name: Super-Linter
env:
  GITHUB_SHA_KEY: ${{github.sha}}

on:
  push:
    branches:
      - main
        

jobs:
  my_testing:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Print hello world
        run: |
          echo "Hello world" 
          echo "this is a github sha key: " ${{GITHUB_SHA_KEY}}



  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
