name: Super-Linter
env:
  'GITH': ${{ github.sha }}
  
on:
  push:
    branches:
      - main
        

jobs:
  my_testing:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Print hello world
        run: |
          echo "Hello world" 
          echo "this is a github sha key: " ${{env.GITH}}


  uploading_repos:
              runs-on: ubuntu-latest
              needs: [my_testing]
              
              steps:
                  - name: Empty Directory pick
                    run: ls -la
                    
                  - name: Uploading directory 
                    uses: actions/checkout@v1
                    
                  - name: Showing directory
                    run: ls -la
                    
                  - name: Zip file
                    run: zip -r "my_file.zip" ./ -x *.git*
                  
                

         
      
        
 
